/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkforceRouteImport } from './routes/_app/workforce'
import { Route as AppWidgetRouteImport } from './routes/_app/widget'
import { Route as AppVisitorsRouteImport } from './routes/_app/visitors'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppSuperAdminRouteImport } from './routes/_app/super-admin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiCenterRouteImport } from './routes/_app/ai-center'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppWidgetRoute = AppWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminRoute = AppSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-center': typeof AppAiCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/campaigns': typeof AppCampaignsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/super-admin': typeof AppSuperAdminRoute
  '/tickets': typeof AppTicketsRoute
  '/visitors': typeof AppVisitorsRoute
  '/widget': typeof AppWidgetRoute
  '/workforce': typeof AppWorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-center': typeof AppAiCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/campaigns': typeof AppCampaignsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/super-admin': typeof AppSuperAdminRoute
  '/tickets': typeof AppTicketsRoute
  '/visitors': typeof AppVisitorsRoute
  '/widget': typeof AppWidgetRoute
  '/workforce': typeof AppWorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-center': typeof AppAiCenterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/super-admin': typeof AppSuperAdminRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/visitors': typeof AppVisitorsRoute
  '/_app/widget': typeof AppWidgetRoute
  '/_app/workforce': typeof AppWorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-center'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/campaigns'
    | '/crm'
    | '/dashboard'
    | '/inbox'
    | '/integrations'
    | '/organization'
    | '/settings'
    | '/super-admin'
    | '/tickets'
    | '/visitors'
    | '/widget'
    | '/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-center'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/campaigns'
    | '/crm'
    | '/dashboard'
    | '/inbox'
    | '/integrations'
    | '/organization'
    | '/settings'
    | '/super-admin'
    | '/tickets'
    | '/visitors'
    | '/widget'
    | '/workforce'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-center'
    | '/_app/analytics'
    | '/_app/automation'
    | '/_app/billing'
    | '/_app/campaigns'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/integrations'
    | '/_app/organization'
    | '/_app/settings'
    | '/_app/super-admin'
    | '/_app/tickets'
    | '/_app/visitors'
    | '/_app/widget'
    | '/_app/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workforce': {
      id: '/_app/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/widget': {
      id: '/_app/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AppWidgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin': {
      id: '/_app/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AppSuperAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-center': {
      id: '/_app/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuperAdminRoute: typeof AppSuperAdminRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
  AppWidgetRoute: typeof AppWidgetRoute
  AppWorkforceRoute: typeof AppWorkforceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCenterRoute: AppAiCenterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBillingRoute: AppBillingRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuperAdminRoute: AppSuperAdminRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
  AppWidgetRoute: AppWidgetRoute,
  AppWorkforceRoute: AppWorkforceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
